#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Complete Mt Challenger Project Dossier - Terminal Output"""

import sys
from datetime import datetime

# Fix encoding for Windows console
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')

def print_section(title, char="="):
    """Print section header"""
    width = 120
    print(f"\n{char * width}")
    print(f"{title.center(width)}")
    print(f"{char * width}\n")

def print_subsection(title):
    """Print subsection header"""
    print(f"\n{'─' * 120}")
    print(f"  {title}")
    print(f"{'─' * 120}")

def print_item(label, value, indent=0):
    """Print labeled item"""
    spacing = "  " * indent
    print(f"{spacing}• {label:30s} {value}")

def print_status(status, description):
    """Print status with icon"""
    icons = {
        "CRITICAL": "🚨",
        "BLOCKED": "❌",
        "WARNING": "⚠️",
        "IN_PROGRESS": "⏳",
        "COMPLETED": "✅",
        "PENDING": "🔷"
    }
    icon = icons.get(status, "•")
    print(f"  {icon} {description}")

def main():
    print_section("MT CHALLENGER WIND FARM + BESS PROJECT", "═")
    print_section("COMPLETE PROJECT DOSSIER", "═")
    print(f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}")
    print(f"Report Type: EXECUTIVE BRIEFING - ROBBY HANDOVER PREPARATION")

    # ========================================
    # PROJECT IDENTIFICATION
    # ========================================
    print_section("PROJECT IDENTIFICATION")

    print_item("Project Name:", "Mt Challenger Wind Farm + BESS Grid Connection Studies")
    print_item("Project Code:", "Q7193")
    print_item("Project Type:", "Powerlink Queensland (PLQ) Connection Studies")
    print_item("Client:", "Alinta Energy")
    print_item("Client Sector:", "Renewable Energy Developer")
    print()
    print_item("Primary Contact:", "Cedric Banda (Senior Grid Connections Engineer)")
    print_item("Email:", "cedric.banda@alintaenergy.com.au")
    print_item("Phone:", "0437 956 948")
    print()
    print_item("Other Contacts:", "Sam Withers, Tjedza Masola (Alinta)")
    print_item("Client Legal:", "Alinta Legal Team (reviewing contract)")

    # ========================================
    # VYSUS TEAM
    # ========================================
    print_section("VYSUS TEAM STRUCTURE")

    print_subsection("DEPARTING")
    print_item("Project Lead (Leaving):", "Robby Palackal - Team Lead Australia")
    print_item("Email:", "robby.palackal@vysusgroup.com")
    print_item("Role:", "Commercial lead, client relationship, proposal development")

    print_subsection("ONGOING TEAM (POST-HANDOVER)")
    print_item("Operations Director:", "Chris Marinelli - chris.marinelli@vysusgroup.com")
    print_item("Technical Lead:", "Tony Morton - tony.morton@vysusgroup.com")
    print_item("Technical Support:", "Naveenkumar Rajagopal")
    print_item("Contracts/Legal:", "Graham (Shared-Contract Reviews)")
    print_item("Status:", "TRANSITION IN PROGRESS - Handover meeting TODAY")

    # ========================================
    # PROJECT SCOPE
    # ========================================
    print_section("PROJECT SCOPE & DELIVERABLES")

    print_subsection("TECHNICAL SCOPE")
    print("  Wind Farm + Battery Energy Storage System (BESS) connection to Powerlink Queensland grid")
    print()
    print_item("Phase 1 (Pre-Christmas):", "Capacity Assessment")
    print_item("", "- Network loading analysis (66kV significant loading identified)")
    print_item("", "- PowerFactory modeling (Ergon model available)")
    print_item("", "- Concept design finalization")

    print()
    print_item("Phase 2 (Jan/Feb 2026):", "Connection Application")
    print_item("", "- Compliance assessment")
    print_item("", "- Detailed technical studies")
    print_item("", "- Application documentation")

    print_subsection("METHODOLOGY")
    print_item("Approach:", "Powerlink Queensland (PLQ) Three-Stage Methodology")
    print_item("Challenge:", "Required complete proposal rewrite from Vysus standard template")
    print_item("Status:", "✅ Rewritten by Tony Morton, Approved Oct 13, 2025")

    print_subsection("KEY TECHNICAL CONSIDERATIONS")
    print_status("WARNING", "PLQ enquiry response shows SIGNIFICANT LOADING on 66kV network")
    print_status("IN_PROGRESS", "PowerFactory model from Ergon available for detailed assessment")
    print_status("PENDING", "Harmonics analysis methodology aligned to PLQ approach")

    # ========================================
    # PROJECT TIMELINE
    # ========================================
    print_section("PROJECT TIMELINE - CHRONOLOGICAL HISTORY")

    print_subsection("OCTOBER 2025 - PROPOSAL & APPROVAL")
    print()
    print("  Oct 10, 2025:")
    print_status("COMPLETED", "Robby urgently requests PLQ methodology rewrite from Tony Morton")
    print_status("COMPLETED", "Proposal due SAME DAY - Tony completes rewrite")
    print_status("COMPLETED", "Proposal restructured to PLQ three-stage approach")
    print()
    print("  Oct 13, 2025:")
    print_status("COMPLETED", "Thomas approves Mt Challenger project to proceed")
    print_status("COMPLETED", "Project green-lit internally")

    print_subsection("LATE OCTOBER - EARLY NOVEMBER 2025 - CONTRACT NEGOTIATIONS")
    print()
    print("  Oct 29, 2025:")
    print_status("COMPLETED", "Robby submits Master Consultancy Agreement (MCA) to Vysus legal")
    print_status("WARNING", "Client requesting feedback by that Friday")
    print_status("WARNING", "Internal delays due to holiday absences")
    print()
    print("  Nov 5, 2025:")
    print_status("WARNING", "Client chasing: 'Any update from your legal team on the MCA?'")
    print_status("COMPLETED", "Robby apologizes for delay, escalates internally")
    print()
    print("  Nov 6, 2025:")
    print_status("COMPLETED", "Graham (Vysus contracts) completes review")
    print("                  Assessment: 'Pretty reasonable contract, nothing too onerous'")
    print("                  Strategic note: 'Linked to higher value opportunity'")
    print("                  Flexibility: 'Can loosen our stance to get this over the line'")
    print_status("COMPLETED", "Robby sends contract redlines with tracked changes to Alinta")

    print_subsection("MID NOVEMBER 2025 - CLIENT PROGRESS & PRESSURE")
    print()
    print("  Nov 10, 2025:")
    print_status("COMPLETED", "Client received all OPDM snapshots and RUGs (technical data)")
    print_status("BLOCKED", "Waiting for Alinta MANAGEMENT APPROVAL (timeline unknown)")
    print_status("IN_PROGRESS", "Scope timing clarified:")
    print("                  - Capacity assessment: Before Christmas 2025")
    print("                  - Connection Application: End Jan/Early Feb 2026")
    print()
    print("  Nov 13, 2025:")
    print_status("WARNING", "Graham chasing: 'Conscious we have this to close this month'")
    print_status("WARNING", "Vysus internal pressure to sign by end of November")

    print_subsection("NOVEMBER 18, 2025 - INSURANCE ISSUE EMERGES")
    print()
    print("  Morning:")
    print_status("IN_PROGRESS", "Robby follows up: 'Did your team get a chance to review the T&Cs?'")
    print()
    print("  Afternoon:")
    print_status("CRITICAL", "MAJOR BLOCKER IDENTIFIED - Insurance Coverage Gap:")
    print("                  Client Legal: '$3M public liability insurance is quite low'")
    print("                  Client Expectation: '$20M is common for these projects'")
    print("                  Gap: 6.7x difference (DEAL BREAKER POTENTIAL)")
    print_status("PENDING", "Client: 'Will wait for rest of comments' - MORE ISSUES MAY COME")
    print()
    print("  Evening (22:15):")
    print_status("IN_PROGRESS", "Robby escalates to Graham: 'Could you please review...'")
    print()
    print("  Evening (22:28):")
    print_status("IN_PROGRESS", "Robby responds to Cedric: 'I will come back to you...'")
    print("                  Robby states: '$3M is quite typical for services we provide'")
    print("                  Promises to check with contracts team")

    print_subsection("NOVEMBER 19-24, 2025 - CURRENT STATUS")
    print()
    print("  Nov 19-24:")
    print_status("BLOCKED", "NO RESPONSE FROM GRAHAM on insurance issue (6 DAYS)")
    print_status("BLOCKED", "NO RESPONSE TO CEDRIC on insurance (6 DAYS)")
    print_status("PENDING", "Alinta legal review still in progress")
    print_status("PENDING", "Alinta management approval timeline unknown")
    print_status("WARNING", "November deadline at serious risk")
    print()
    print("  TODAY - Nov 24, 2025:")
    print_status("CRITICAL", "HANDOVER MEETING WITH CEDRIC SCHEDULED")
    print_status("CRITICAL", "ROBBY DEPARTING - Team transition underway")
    print_status("CRITICAL", "MUST ADDRESS INSURANCE ISSUE TODAY")

    # ========================================
    # CRITICAL ISSUES
    # ========================================
    print_section("CRITICAL ISSUES & BLOCKERS", "═")

    print_subsection("🚨 ISSUE #1: PUBLIC LIABILITY INSURANCE GAP (CRITICAL)")
    print()
    print_item("Vysus Position:", "$3 million coverage")
    print_item("Client Expectation:", "$20 million coverage (industry standard)")
    print_item("Gap:", "6.7x difference / $17M shortfall")
    print_item("Status:", "UNRESOLVED - 6 days since client raised")
    print_item("Risk Level:", "DEAL BREAKER - Can kill entire project")
    print()
    print("  Client Signal:")
    print("    'One key comment is that the proposed amount for public liability")
    print("    insurance ($3 million) is quite low compared to $20 million for")
    print("    public liability insurance which is common.'")
    print()
    print("  ACTIONS REQUIRED:")
    print_status("CRITICAL", "Get quotes for $10M, $15M, $20M coverage TODAY")
    print_status("CRITICAL", "Calculate cost delta for each level")
    print_status("CRITICAL", "Decide internal position BEFORE handover meeting")
    print_status("CRITICAL", "Present solution to Cedric TODAY (don't leave hanging)")
    print()
    print("  NEGOTIATION OPTIONS:")
    print("    Option A: Hold at $3M with detailed justification (HIGH RISK)")
    print("              - Benchmark similar PLQ study projects")
    print("              - Emphasize desk-based work, no construction risk")
    print("              - May lose deal if client won't budge")
    print()
    print("    Option B: Compromise at $10-12M with cost pass-through (RECOMMENDED)")
    print("              - Shows flexibility, meets client halfway")
    print("              - Add premium delta as line item or rate adjustment")
    print("              - Commercially viable for both parties")
    print()
    print("    Option C: Accept $20M, absorb or pass through cost (STRATEGIC)")
    print("              - If 'higher value opportunity' justifies it")
    print("              - Positions Vysus as serious long-term partner")
    print("              - Removes blocker completely")

    print_subsection("🔷 ISSUE #2: CONTRACT TERMS & CONDITIONS")
    print()
    print_item("Status:", "Partially resolved, pending full legal review")
    print_item("Vysus Legal Review:", "✅ Complete (Nov 6) - 'reasonable contract'")
    print_item("Vysus Redlines Sent:", "✅ Nov 6 with tracked changes")
    print_item("Client Legal Review:", "⏳ In progress - insurance was just 'one key comment'")
    print_item("Risk:", "Unknown additional legal issues may emerge")
    print()
    print("  ACTIONS REQUIRED:")
    print_status("IN_PROGRESS", "Await client's full legal review (beyond insurance)")
    print_status("PENDING", "Confirm Alinta acceptance of Vysus redlines")
    print_status("PENDING", "Address any remaining legal comments promptly")

    print_subsection("🔷 ISSUE #3: CLIENT INTERNAL APPROVALS")
    print()
    print_item("Blocker:", "Alinta management approval required")
    print_item("Timeline:", "UNKNOWN - Cedric has not provided estimate")
    print_item("Dependencies:", "Contract must be finalized first")
    print_item("Impact:", "Cannot start work until approved")
    print()
    print("  Client Status (as of Nov 10):")
    print_status("COMPLETED", "Technical data received (OPDM snapshots, RUGs)")
    print_status("PENDING", "Management approval process (no timeline given)")
    print()
    print("  ACTIONS REQUIRED:")
    print_status("CRITICAL", "Get approval timeline from Cedric TODAY")
    print_status("IN_PROGRESS", "Understand what's gating management decision")
    print_status("PENDING", "Identify if anything Vysus can do to accelerate")

    print_subsection("🔷 ISSUE #4: POWERLINK METHODOLOGY COMPLEXITY")
    print()
    print_item("Challenge:", "PLQ has unique three-stage approach vs Vysus standard")
    print_item("Impact:", "Required complete proposal rewrite (Oct 10)")
    print_item("Resolution:", "✅ RESOLVED - Tony Morton completed rewrite")
    print_item("Current Status:", "✅ Approved, no longer an issue")
    print()
    print("  Lesson Learned:")
    print("    Future PLQ projects now have template/methodology established")

    print_subsection("🔷 ISSUE #5: 66kV NETWORK LOADING (TECHNICAL RISK)")
    print()
    print_item("Issue:", "PLQ enquiry shows 'significant loading' on 66kV network")
    print_item("Impact:", "May require additional analysis / expanded scope")
    print_item("Mitigation:", "PowerFactory model available from Ergon for detailed work")
    print_item("Status:", "Acknowledged but not yet analyzed in detail")
    print()
    print("  ACTIONS REQUIRED:")
    print_status("PENDING", "Discuss with Cedric in capacity assessment planning")
    print_status("PENDING", "Confirm if scope/fee adjustment needed for 66kV analysis")
    print_status("IN_PROGRESS", "Finalize key items to investigate once MCA signed")

    print_subsection("🔷 ISSUE #6: ROBBY DEPARTURE & TEAM TRANSITION")
    print()
    print_item("Challenge:", "Project lead leaving mid-negotiation")
    print_item("Risk:", "Client confidence, continuity concerns")
    print_item("Timing:", "Handover meeting TODAY (Nov 24)")
    print_item("Opportunity:", "Position as upgrade to deeper team structure")
    print()
    print("  MITIGATION STRATEGY:")
    print_status("IN_PROGRESS", "Chris Marinelli (Ops Director) taking commercial lead")
    print_status("IN_PROGRESS", "Tony Morton (already core to project) technical lead")
    print_status("CRITICAL", "Present team structure as STRENGTH not weakness")
    print_status("CRITICAL", "Show Cedric nothing changes in delivery capability")

    # ========================================
    # CURRENT STATUS SUMMARY
    # ========================================
    print_section("CURRENT STATUS SUMMARY")

    print_subsection("✅ COMPLETED ITEMS")
    print_status("COMPLETED", "Proposal submitted and approved internally (Oct 13)")
    print_status("COMPLETED", "PLQ methodology aligned and accepted")
    print_status("COMPLETED", "Vysus legal review complete (Nov 6)")
    print_status("COMPLETED", "Contract redlines sent to client (Nov 6)")
    print_status("COMPLETED", "Technical data received by client (OPDM, RUGs)")
    print_status("COMPLETED", "Powerlink approach rewritten and approved")

    print_subsection("⏳ IN PROGRESS")
    print_status("IN_PROGRESS", "Insurance coverage discussion ($3M vs $20M) - 6 DAYS PENDING")
    print_status("IN_PROGRESS", "Alinta legal review (beyond insurance issue)")
    print_status("IN_PROGRESS", "Alinta management approval process")
    print_status("IN_PROGRESS", "Team handover from Robby to Chris/Tony")

    print_subsection("❌ BLOCKED / CRITICAL")
    print_status("BLOCKED", "Contract signature - pending insurance resolution")
    print_status("BLOCKED", "Project kickoff - pending contract + approvals")
    print_status("CRITICAL", "Insurance decision overdue (internal)")
    print_status("CRITICAL", "November deadline at risk (13 days since Graham's push)")
    print_status("CRITICAL", "Client waiting 6 days for insurance response")

    # ========================================
    # STRATEGIC CONTEXT
    # ========================================
    print_section("STRATEGIC CONTEXT")

    print_subsection("WHY THIS PROJECT MATTERS TO VYSUS")
    print()
    print_item("1. Gateway Project:", "Graham (contracts): 'Linked to higher value opportunity'")
    print_item("", "- This is a door-opener to larger Alinta portfolio")
    print_item("", "- Success here = future work pipeline")
    print()
    print_item("2. Market Positioning:", "First PLQ project with major renewable developer")
    print_item("", "- Establishes Vysus PLQ methodology credentials")
    print_item("", "- Queensland market entry/expansion")
    print()
    print_item("3. Reference Value:", "Alinta is credible client name for future bids")
    print_item("", "- Renewable energy sector growth market")
    print_item("", "- PLQ projects increasing with renewable buildout")
    print()
    print_item("4. Commercial Intent:", "Contracts team willing to 'loosen stance' to win")
    print_item("", "- Internal recognition this is strategically important")
    print_item("", "- Not just a transactional project")

    print_subsection("CLIENT SIGNALS & BEHAVIOR")
    print()
    print("  POSITIVE INDICATORS:")
    print_status("COMPLETED", "Client moving forward with internal approvals")
    print_status("COMPLETED", "Client gathered technical data (OPDM, RUGs)")
    print_status("COMPLETED", "Cedric responsive and communicative")
    print_status("COMPLETED", "Timeline pressure (want to start before Christmas)")
    print_status("COMPLETED", "Client clarifying phased approach (capacity → connection)")
    print()
    print("  CAUTIONARY SIGNALS:")
    print_status("WARNING", "Legal team not rubber-stamping - active, thorough review")
    print_status("WARNING", "Insurance issue flagged explicitly as concern")
    print_status("WARNING", "Cedric waiting for 'rest of comments' - more may come")
    print_status("WARNING", "Management approval timeline not shared (lack of urgency?)")
    print()
    print("  OVERALL CLIENT POSTURE:")
    print("    • Serious and engaged, but deliberate and risk-conscious")
    print("    • Not desperate to sign - will walk if terms don't work")
    print("    • Professional procurement approach (legal rigor)")
    print("    • Want to move forward but won't compromise on requirements")

    print_subsection("COMPETITIVE LANDSCAPE")
    print()
    print_item("Risk:", "If Vysus can't meet $20M insurance, client has alternatives")
    print_item("Advantage:", "PLQ methodology expertise (Tony's rewrite)")
    print_item("Timing:", "Client wants December start - switching vendors delays them")
    print_item("Leverage:", "Limited - pre-signature, client can walk easily")

    # ========================================
    # FINANCIAL / COMMERCIAL
    # ========================================
    print_section("COMMERCIAL & FINANCIAL")

    print_subsection("CONTRACT VALUE")
    print_item("Status:", "NOT DISCLOSED in email thread")
    print_item("Structure:", "Master Consultancy Agreement (MCA)")
    print_item("Phasing:", "Phase 1 (Capacity) + Phase 2 (Connection)")
    print_item("Strategic Value:", "Gateway to 'higher value opportunity' per contracts")

    print_subsection("PRICING & INSURANCE IMPACT")
    print()
    print("  Current Insurance: $3M public liability")
    print("  Client Requirement: $20M public liability")
    print()
    print("  COST IMPLICATIONS (UNKNOWN - NEED QUOTES):")
    print_item("Baseline:", "$3M coverage = current premium (unknown $)")
    print_item("Option 1:", "$10M coverage = +$X premium (GET QUOTE)")
    print_item("Option 2:", "$15M coverage = +$Y premium (GET QUOTE)")
    print_item("Option 3:", "$20M coverage = +$Z premium (GET QUOTE)")
    print()
    print("  PASS-THROUGH OPTIONS:")
    print("    • Add as reimbursable line item")
    print("    • Adjust hourly rates proportionally")
    print("    • Absorb cost if strategic value justifies")
    print("    • Split difference with client")

    print_subsection("PAYMENT TERMS")
    print_item("Status:", "Under negotiation (MCA being finalized)")
    print_item("Known Issues:", "Insurance coverage is primary commercial sticking point")

    # ========================================
    # ACTION ITEMS & NEXT STEPS
    # ========================================
    print_section("ACTION ITEMS & NEXT STEPS", "═")

    print_subsection("🚨 IMMEDIATE - BEFORE HANDOVER MEETING (TODAY)")
    print()
    print("  CRITICAL PATH ITEMS:")
    print_status("CRITICAL", "Internal huddle: Chris + Graham + [team]")
    print("               - DECIDE insurance position ($3M / $10M / $20M)")
    print("               - GET QUOTES if increasing coverage")
    print("               - ALIGN on negotiation strategy")
    print()
    print_status("CRITICAL", "Prepare handover presentation materials:")
    print("               - RACI chart (who owns what post-Robby)")
    print("               - Project status one-pager")
    print("               - Timeline with milestones")
    print("               - Clear answer on insurance")
    print()
    print_status("CRITICAL", "Brief all attendees on meeting roles:")
    print("               - Chris: Commercial lead, opens/closes, insurance answer")
    print("               - Tony: Technical lead, PLQ methodology, delivery plan")
    print("               - Robby: Warm handoff, validates team, then fades")
    print("               - Graham: Standby for contract questions")

    print_subsection("⏰ TODAY - DURING HANDOVER MEETING")
    print()
    print("  MEETING OBJECTIVES:")
    print_status("CRITICAL", "Project confidence - Vysus has this under control")
    print_status("CRITICAL", "Team credibility - stronger post-Robby, not weaker")
    print_status("CRITICAL", "Insurance resolution - present solution, not problem")
    print_status("CRITICAL", "Lock timeline - get Cedric's commitments on approvals")
    print()
    print("  KEY MESSAGES TO DELIVER:")
    print("    1. 'You're getting a stronger team - dedicated specialists vs. one generalist'")
    print("    2. 'Technical delivery unchanged - Tony was core from day one'")
    print("    3. 'Insurance issue addressed - here's our solution' [present options]")
    print("    4. 'We're committed to Dec start - what do you need from your side?'")
    print("    5. 'Let's lock next steps so we hit Christmas timeline'")
    print()
    print("  QUESTIONS TO ASK CEDRIC:")
    print_status("CRITICAL", "When will Alinta legal review be complete?")
    print_status("CRITICAL", "What's the management approval timeline?")
    print_status("CRITICAL", "Does resolving insurance clear the legal review?")
    print_status("CRITICAL", "Who is day-to-day technical contact on your side?")
    print_status("CRITICAL", "What deliverables do you need by Dec 20 for management?")

    print_subsection("📅 POST-MEETING (WITHIN 24-48 HOURS)")
    print()
    print_status("CRITICAL", "Send insurance position IN WRITING (per meeting commitment)")
    print_status("CRITICAL", "Send meeting notes with action items clearly assigned")
    print_status("IN_PROGRESS", "Follow up on Alinta legal review completion date")
    print_status("IN_PROGRESS", "Provide detailed resource plan & timeline to Cedric")
    print_status("IN_PROGRESS", "Schedule follow-up meeting for Nov 27-28 to finalize contract")

    print_subsection("🎯 THIS WEEK (NOV 25-29)")
    print()
    print_status("CRITICAL", "Respond to full Alinta legal comments within 48hrs of receipt")
    print_status("CRITICAL", "Resolve insurance coverage (quote, decide, negotiate)")
    print_status("CRITICAL", "Finalize contract terms")
    print_status("CRITICAL", "Get contract SIGNED by Nov 29 (end of month)")
    print_status("IN_PROGRESS", "Confirm management approval status")
    print_status("IN_PROGRESS", "Lock resource allocation for Dec capacity assessment")

    print_subsection("📅 EARLY DECEMBER (DEC 2-6)")
    print()
    print_status("PENDING", "Kick off capacity assessment work")
    print_status("PENDING", "First technical coordination call with Cedric team")
    print_status("PENDING", "Access PowerFactory model from Ergon")
    print_status("PENDING", "Begin 66kV loading analysis")

    print_subsection("📅 PRE-CHRISTMAS (DEC 9-20)")
    print()
    print_status("PENDING", "Deliver capacity assessment phase 1 findings")
    print_status("PENDING", "Present to Alinta management for approval")
    print_status("PENDING", "Finalize concept design")
    print_status("PENDING", "Plan Phase 2 (Connection Application) for Jan/Feb")

    # ========================================
    # RISK ASSESSMENT
    # ========================================
    print_section("RISK ASSESSMENT & MITIGATION")

    print_subsection("DEAL HEALTH SCORE: 6.5 / 10")
    print()
    print("  POSITIVE FACTORS (+):")
    print_status("COMPLETED", "Project approved internally at Vysus (Thomas)")
    print_status("COMPLETED", "Client engaged and responsive (Cedric)")
    print_status("COMPLETED", "Contract terms 'reasonable' per Vysus legal")
    print_status("COMPLETED", "Technical data being gathered by client")
    print_status("COMPLETED", "Clear scope and methodology agreed")
    print_status("COMPLETED", "Technical team continuity (Tony stays)")
    print()
    print("  RISK FACTORS (-):")
    print_status("CRITICAL", "Insurance gap - major commercial issue")
    print_status("BLOCKED", "Legal review incomplete (6 days since insurance raised)")
    print_status("BLOCKED", "Management approval pending (timeline unknown)")
    print_status("WARNING", "November deadline slipping (6 days no insurance response)")
    print_status("WARNING", "Unknown additional legal comments may emerge")
    print_status("WARNING", "Leadership transition during negotiation")
    print()
    print("  OVERALL ASSESSMENT:")
    print("    Deal is SALVAGEABLE with quick insurance resolution.")
    print("    Client is serious but will walk if requirements not met.")
    print("    Time-sensitive - Dec start requires Nov signature.")
    print("    Strategic value justifies flexibility on Vysus side.")

    print_subsection("KEY RISKS & MITIGATION")
    print()
    print("  RISK #1: Insurance issue kills deal")
    print("    Probability: MEDIUM-HIGH if not resolved this week")
    print("    Impact: HIGH (lose project + future Alinta work)")
    print("    Mitigation:")
    print_status("CRITICAL", "Present solution TODAY in handover meeting")
    print_status("CRITICAL", "Get quotes and make decision within 24 hours")
    print_status("CRITICAL", "Show flexibility - don't die on $3M hill")
    print()
    print("  RISK #2: Client loses confidence due to Robby departure")
    print("    Probability: MEDIUM without strong handover")
    print("    Impact: HIGH (project stalls or client walks)")
    print("    Mitigation:")
    print_status("IN_PROGRESS", "Position as upgrade (deeper team)")
    print_status("IN_PROGRESS", "Chris provides senior leadership visibility")
    print_status("IN_PROGRESS", "Tony demonstrates technical continuity")
    print_status("IN_PROGRESS", "Professional, prepared handover meeting")
    print()
    print("  RISK #3: Timeline slips past December start window")
    print("    Probability: HIGH if insurance + approvals not resolved this week")
    print("    Impact: MEDIUM (delays project, may lose priority)")
    print("    Mitigation:")
    print_status("CRITICAL", "Aggressive timeline push in handover meeting")
    print_status("CRITICAL", "Get Cedric's commitment on approval dates")
    print_status("CRITICAL", "Remove blockers on Vysus side (insurance decision)")
    print()
    print("  RISK #4: Additional legal issues emerge beyond insurance")
    print("    Probability: MEDIUM (Cedric said 'rest of comments' coming)")
    print("    Impact: MEDIUM (further delays, potential deal-breakers)")
    print("    Mitigation:")
    print_status("IN_PROGRESS", "Ask Cedric for full legal review timeline TODAY")
    print_status("IN_PROGRESS", "Identify all outstanding items in handover meeting")
    print_status("IN_PROGRESS", "Graham on standby to respond quickly")
    print()
    print("  RISK #5: Management approval delayed indefinitely")
    print("    Probability: LOW-MEDIUM (client seems engaged)")
    print("    Impact: HIGH (cannot start work)")
    print("    Mitigation:")
    print_status("CRITICAL", "Get visibility on approval process from Cedric")
    print_status("IN_PROGRESS", "Understand what management needs to approve")
    print_status("IN_PROGRESS", "Offer to present directly to management if helpful")

    # ========================================
    # COMMUNICATION PLAN
    # ========================================
    print_section("COMMUNICATION & STAKEHOLDER MANAGEMENT")

    print_subsection("COMMUNICATION MATRIX")
    print()
    print("  EXTERNAL STAKEHOLDERS:")
    print()
    print("  Cedric Banda (Alinta - Technical Lead)")
    print_item("  Role:", "Day-to-day technical contact, project coordination")
    print_item("  Messages:", "Continuity, technical capability, timeline commitment")
    print_item("  Frequency:", "Weekly (or as needed during negotiation)")
    print_item("  Owner:", "Chris (commercial) + Tony (technical)")
    print()
    print("  Alinta Legal Team")
    print_item("  Role:", "Contract review, risk management")
    print_item("  Messages:", "Insurance resolution, T&Cs finalization")
    print_item("  Frequency:", "As needed (via Cedric)")
    print_item("  Owner:", "Graham (Vysus contracts)")
    print()
    print("  Alinta Management")
    print_item("  Role:", "Approval authority, strategic oversight")
    print_item("  Messages:", "Project value, Vysus capability, risk mitigation")
    print_item("  Frequency:", "Via Cedric (or direct if requested)")
    print_item("  Owner:", "Chris")
    print()
    print("  INTERNAL STAKEHOLDERS:")
    print()
    print("  Chris Marinelli (Vysus Ops Director)")
    print_item("  Role:", "Decision authority, commercial lead post-Robby")
    print_item("  Messages:", "Status updates, escalations, approvals")
    print_item("  Frequency:", "Daily during negotiation")
    print_item("  Owner:", "All team members")
    print()
    print("  Graham (Vysus Contracts)")
    print_item("  Role:", "Legal review, insurance decisions, T&Cs")
    print_item("  Messages:", "Client feedback, negotiation strategy")
    print_item("  Frequency:", "As needed (currently CRITICAL - daily)")
    print_item("  Owner:", "Chris / Robby")
    print()
    print("  Tony Morton (Technical Lead)")
    print_item("  Role:", "PLQ methodology, technical delivery")
    print_item("  Messages:", "Scope, timeline, resource needs")
    print_item("  Frequency:", "Weekly project reviews")
    print_item("  Owner:", "Chris")

    # ========================================
    # LESSONS LEARNED
    # ========================================
    print_section("LESSONS LEARNED (TO DATE)")

    print_subsection("WHAT'S WORKING WELL")
    print_status("COMPLETED", "Tony's PLQ methodology expertise - client accepted rewrite")
    print_status("COMPLETED", "Technical team capability - no concerns from client")
    print_status("COMPLETED", "Contracts review (Graham) - identified reasonable terms")
    print_status("COMPLETED", "Client relationship (Robby) - built good rapport with Cedric")

    print_subsection("WHAT NEEDS IMPROVEMENT")
    print_status("WARNING", "Response time on client issues (6 days on insurance)")
    print_status("WARNING", "Internal coordination (legal team delays)")
    print_status("WARNING", "Proactive issue identification (insurance should have been caught in proposal)")
    print_status("WARNING", "Timeline management (November deadline slipping)")

    print_subsection("RECOMMENDATIONS FOR FUTURE")
    print()
    print("  • Include insurance requirements discussion in proposal stage")
    print("  • Set internal SLAs for legal review turnaround")
    print("  • Maintain weekly client touchpoints during negotiation")
    print("  • Assign dedicated commercial lead with decision authority")
    print("  • Create PLQ project template based on this experience")

    # ========================================
    # HANDOVER CHECKLIST
    # ========================================
    print_section("HANDOVER MEETING CHECKLIST", "═")

    print_subsection("✅ PRE-MEETING PREPARATION (30 MIN BEFORE)")
    print()
    print_status("CRITICAL", "Insurance decision finalized internally")
    print_status("CRITICAL", "RACI chart prepared (roles & responsibilities)")
    print_status("CRITICAL", "Status one-pager ready to screen share")
    print_status("CRITICAL", "All attendees briefed on their speaking roles")
    print_status("CRITICAL", "Questions for Cedric prepared")
    print_status("CRITICAL", "Next meeting date ready to propose")
    print_status("CRITICAL", "Answer prepared for 'why is Robby leaving' if asked")

    print_subsection("📋 MEETING AGENDA (60 MIN)")
    print()
    print("  [5 min]  Robby: Handover context & warm introduction")
    print("  [10 min] Chris: New team structure & continuity message")
    print("  [20 min] Chris: Project status & INSURANCE RESOLUTION")
    print("  [15 min] Tony: Technical coordination & delivery plan")
    print("  [10 min] Chris: Action items, next steps, next meeting")

    print_subsection("🎯 KEY OBJECTIVES")
    print()
    print_status("CRITICAL", "Client confidence in team transition")
    print_status("CRITICAL", "Insurance issue resolved or clear path forward")
    print_status("CRITICAL", "Timeline commitments from both sides")
    print_status("CRITICAL", "Next meeting scheduled (Nov 27-28)")

    print_subsection("📝 POST-MEETING DELIVERABLES")
    print()
    print_status("CRITICAL", "Meeting notes with action items (within 2 hours)")
    print_status("CRITICAL", "Insurance position in writing (within 2 hours)")
    print_status("CRITICAL", "Resource plan & timeline (within 24 hours)")
    print_status("CRITICAL", "Follow-up meeting invitation (within 24 hours)")

    # ========================================
    # QUICK REFERENCE
    # ========================================
    print_section("QUICK REFERENCE - KEY FACTS")

    print_subsection("ELEVATOR PITCH")
    print()
    print("  Mt Challenger is a Powerlink Queensland grid connection study for")
    print("  Alinta Energy's wind farm + battery project. We're in final contract")
    print("  negotiations with one major blocker: insurance coverage ($3M vs $20M).")
    print("  Robby is handing over to Chris (commercial) and Tony (technical) today.")
    print("  This is a strategic gateway project to larger Alinta opportunities.")
    print("  We need to resolve insurance TODAY and sign contract by Nov 29 to")
    print("  start capacity assessment work before Christmas as client needs.")

    print_subsection("THE ASK (TO GRAHAM/CONTRACTS)")
    print()
    print("  'Graham - we need an insurance decision NOW. Client has been waiting")
    print("  6 days. We're meeting with them TODAY. Can we go to $10M or $20M?")
    print("  What are the quotes? This is linked to higher value work - your words.")
    print("  Help us close this.''")

    print_subsection("THE MESSAGE (TO CEDRIC)")
    print()
    print("  'Cedric - on insurance, we've reviewed with our team and insurers.")
    print("  We can accommodate [DECISION]. Here's how it works financially.")
    print("  On the handover, you're getting an upgrade - dedicated specialists")
    print("  instead of Robby wearing all the hats. Tony's been core from day one.")
    print("  We're committed to your December start. What do you need from your")
    print("  legal and management teams to make that happen?'")

    print_subsection("KEY DATES")
    print()
    print_item("Oct 10:", "Proposal submitted")
    print_item("Oct 13:", "Project approved")
    print_item("Nov 6:", "Contract redlines sent")
    print_item("Nov 10:", "Client waiting management approval")
    print_item("Nov 18:", "Insurance issue raised")
    print_item("Nov 24:", "TODAY - Handover meeting")
    print_item("Nov 29:", "Target contract signature (end of month)")
    print_item("Dec 2-6:", "Target project kickoff")
    print_item("Dec 20:", "Pre-Christmas deliverable")
    print_item("Jan/Feb:", "Phase 2 - Connection Application")

    print_subsection("KEY PEOPLE")
    print()
    print("  CLIENT SIDE:")
    print_item("  Cedric Banda:", "Senior Engineer, day-to-day contact")
    print_item("  Sam Withers:", "Alinta (role unclear)")
    print_item("  Tjedza Masola:", "Alinta (role unclear)")
    print_item("  Alinta Legal:", "Reviewing contract, flagged insurance")
    print_item("  Alinta Management:", "Approval authority (unknown timeline)")
    print()
    print("  VYSUS SIDE:")
    print_item("  Robby Palackal:", "DEPARTING - was project lead")
    print_item("  Chris Marinelli:", "Ops Director - NEW commercial lead")
    print_item("  Tony Morton:", "Technical lead - CONTINUITY")
    print_item("  Naveen Rajagopal:", "Technical support")
    print_item("  Graham:", "Contracts - NEEDS TO RESPOND ON INSURANCE")

    print_subsection("KEY NUMBERS")
    print()
    print_item("Project Code:", "Q7193")
    print_item("Current Insurance:", "$3 million")
    print_item("Client Requirement:", "$20 million")
    print_item("Gap:", "$17 million / 6.7x")
    print_item("Days Since Issue Raised:", "6 days (Nov 18 → Nov 24)")
    print_item("Days Until Month End:", "5 business days")
    print_item("Days Until Christmas:", "26 days")

    # ========================================
    # FOOTER
    # ========================================
    print_section("END OF DOSSIER", "═")
    print()
    print("  CRITICAL SUCCESS FACTORS FOR TODAY:")
    print()
    print_status("CRITICAL", "Present insurance solution (not problem)")
    print_status("CRITICAL", "Project team confidence & unity")
    print_status("CRITICAL", "Lock timeline commitments from Cedric")
    print_status("CRITICAL", "Position handover as strength")
    print_status("CRITICAL", "Leave meeting with clear next steps")
    print()
    print("  YOU'VE GOT THIS. Be confident. Be prepared. Be decisive.")
    print()
    print(f"{'═' * 120}\n")

if __name__ == "__main__":
    main()
